### ISSUE TITLE
Couldn't find DDT when trying to install Data::Dump::Tree

### ISSUE THREAD

**Issue by molecules** [nkh/P6-Data-Dump-Tree#30] opened 2017-08-08 21:57 UTC
Is `DDT` a module? I found `Ddt` (https://github.com/kalkin/Ddt). It that what it is supposed to be? I had the following failure when trying to install `Date::Dump::Tree`:

```
zef install Data::Dump::Tree
===> Searching for: Data::Dump::Tree
===> Testing: Data::Dump::Tree:ver('1.5.2'):auth('github:nkh')
===SORRY!===
Could not find DDT at line 3 in:

```

**Comment by nkh** [comment] 2017-08-09 07:13
Hi, DDT is an alias Data::Dump::Tree.

Can you please give me the rest of the message, I need to know line 3 in
which file.

**Comment by nkh** [comment] 2017-08-09 07:32
Hi, I found the file, made the change and pushed a few more small changes. I bumped the version so this should install without problem.

Can you please let me know if the installation when well?

Also, can you please try to use Data::Dump::Tree in a test and also use DDT? It works fine  for me I'd like to understand what is the difference.

Last but not least, if you render something interesting that you can share, just .perl the data structure in a file and send it to me with your DDT call.

I close the ticket as I think the problem will be fixed, don't hesitate to re-open it if necessary.

Cheers, Nadim

**Closed as completed by nkh** 2017-08-09 07:32 UTC

**Comment by molecules** [comment] 2017-08-09 12:59
I don't see a reopen button, but here is the error message:

```
===> Searching for: Data::Dump::Tree
===> Updated cpan mirror: https://raw.githubusercontent.com/ugexe/Perl6-ecosystems/master/cpan.json
===> Updated p6c mirror: http://ecosystem-api.p6c.org/projects.json
===> Testing: Data::Dump::Tree:ver('1.5.2'):auth('github:nkh')
===SORRY!===
Could not find DDT at line 3 in:
    /home/user/.zef/store/P6-Data-Dump-Tree.git/6282ddc42bcc8ed50b02e1136300e553ab5775f9/lib
    /home/user/.perl6
    /path/bio/informatics-core/apps/rakudo-star/rakudo-star-2017.07/install/share/perl6/site
    /path/bio/informatics-core/apps/rakudo-star/rakudo-star-2017.07/install/share/perl6/vendor
    /path/bio/informatics-core/apps/rakudo-star/rakudo-star-2017.07/install/share/perl6
    CompUnit::Repository::AbsolutePath<57714384>
    CompUnit::Repository::NQP<30040536>
    CompUnit::Repository::Perl5<30040576>
===> Testing [FAIL]: Data::Dump::Tree:ver('1.5.2'):auth('github:nkh')
Aborting due to test failure: Data::Dump::Tree:ver('1.5.2'):auth('github:nkh') (use --force-test to override)
  in code  at /path/bio/informatics-core/apps/rakudo-star/rakudo-star-2017.07/install/share/perl6/site/sources/3393EDA469A9E8925A633FF7A533AB41141495DA (Zef::Client) line  in method test at /path/bio/informatics-core/apps/rakudo-star/rakudo-star-2017.07/install/share/perl6/site/sources/3393EDA469A9E8925A633FF7A533AB41141495DA (Zef::Client
  in code  at /path/bio/informatics-core/apps/rakudo-star/rakudo-star-2017.07/install/share/perl6/site/sources/3393EDA469A9E8925A633FF7A533AB41141495DA (Zef::Client) line  in sub  at /path/bio/informatics-core/apps/rakudo-star/rakudo-star-2017.07/install/share/perl6/site/sources/3393EDA469A9E8925A633FF7A533AB41141495DA (Zef::Client) line
  in method install at /path/bio/informatics-core/apps/rakudo-star/rakudo-star-2017.07/install/share/perl6/site/sources/3393EDA469A9E8925A633FF7A533AB41141495DA (Zef::Cli  in sub MAIN at /path/bio/informatics-core/apps/rakudo-star/rakudo-star-2017.07/install/share/perl6/site/sources/ED3033E8712BCF9F6DE53678B14A54705DF211A6 (Zef::CLI) line
  in block <unit> at /path/bio/informatics-core/apps/rakudo-star/rakudo-star-2017.07/install/share/perl6/site/resources/6182CA1C8C9C6ED5BBB3076B522103070B37DDA4 line 1
  in sub MAIN at /path/bio/informatics-core/apps/rakudo-star/rakudo-star-2017.07/install/share/perl6/site/bin/zef line 2
  in block <unit> at /path/bio/informatics-core/apps/rakudo-star/rakudo-star-2017.07/install/share/perl6/site/bin/zef line 2

```

**Comment by nkh** [comment] 2017-08-09 13:33
should be fixed in the latest.

I also go another report of test 04_flat not passing because of different
number of lines than expected. I am working on that one now.

Cheers, N

**Comment by molecules** [comment] 2017-08-09 14:26
I deleted `/home/user/.zef/store/P6-Data-Dump-Tree.git/` and tried reinstalling it with `zef` and got almost identical output. Here is the diff (right is newer output):

```
> ===> Updated cpan mirror: https://raw.githubusercontent.com/ugexe/Perl6-ecosystems/master/cpan.json
> ===> Updated p6c mirror: http://ecosystem-api.p6c.org/projects.json
10,12c12,14
<     CompUnit::Repository::AbsolutePath<57714304>
<     CompUnit::Repository::NQP<30040504>
<     CompUnit::Repository::Perl5<30040544>
---
>     CompUnit::Repository::AbsolutePath<57714384>
>     CompUnit::Repository::NQP<30040536>
>     CompUnit::Repository::Perl5<30040576>

```

Then I reran `zef` using the `--debug` option:


```
===> Searching for: Data::Dump::Tree
===> Found: Data::Dump::Tree:ver('1.5.3'):auth('github:nkh') [via Zef::Repository::Ecosystems<p6c>]
===> Dependencies: Test, Test::META
===> Fetching: Data::Dump::Tree
Fetching with plugin: Zef::Service::Shell::git+{<anon|56022096>}
===> Fetching [OK]: Data::Dump::Tree:ver('1.5.3'):auth('github:nkh') to /home/user/.zef/tmp/P6-Data-Dump-Tree.git
===> Extracting: Data::Dump::Tree
Extracting with plugin: Zef::Service::Shell::git+{<anon|56022096>}
===> Extraction [OK]: Data::Dump::Tree to /home/user/.zef/store/P6-Data-Dump-Tree.git
===> Filtering: Data::Dump::Tree:ver('1.5.2'):auth('github:nkh')
===> Filtering [OK] for Data::Dump::Tree:ver('1.5.2'):auth('github:nkh')
===> # SKIP: No Build.pm for Data::Dump::Tree:ver('1.5.2'):auth('github:nkh')
===> Testing: Data::Dump::Tree:ver('1.5.2'):auth('github:nkh')
Testing with plugin: Zef::Service::TAP+{<anon|56022096>}
t/00_use.t ................... ok
t/01_all.t ................... ok
t/02_META.t .................. ok
t/03_multiple_arguments.t .... ok
t/04_flat.t .................. ok
t/05_class_attributes.t ...... ok
===SORRY!===
Could not find DDT at line 3 in:
    /home/user/.zef/store/P6-Data-Dump-Tree.git/6282ddc42bcc8ed50b02e1136300e553ab5775f9/lib
    /home/user/.perl6
    /path/bio/informatics-core/apps/rakudo-star/rakudo-star-2017.07/install/share/perl6/site
    /path/bio/informatics-core/apps/rakudo-star/rakudo-star-2017.07/install/share/perl6/vendor
    /path/bio/informatics-core/apps/rakudo-star/rakudo-star-2017.07/install/share/perl6
    CompUnit::Repository::AbsolutePath<57714320>
    CompUnit::Repository::NQP<30040488>
    CompUnit::Repository::Perl5<30040528>
t/06_role_attributes.t ....... Dubious, test returned 1
No subtests run
t/10_role.t .................. ok
t/11_class_vs_role.t ......... ok
t/12_extra_standard_roles.t .. ok
t/13_named_captures.t ........ ok
t/14.Match_limit.t ........... ok
t/20_nothing.t ............... ok
t/21_terminal.t .............. ok
t/31_default_base_class.t .... ok
t/32.exception.t ............. ok
t/40_type_Map.t .............. ok
t/41_type_callframe.t ........ ok
t/42_type_Map.t .............. ok
t/43_sequences.t ............. ok
t/44.pair.t .................. ok
t/45_jumctions.t ............. ok
t/46_Bool.t .................. ok
t/47_type_Set.t .............. ok
t/70_sub_interface.t ......... ok
t/71_filter.t ................ ok
t/80_title.t ................. ok
t/81_color.t ................. ok
t/82_max_depth.t ............. ok
t/83_width.t ................. ok
t/90_foldable.t .............. ok
All tests successful.

Test Summary Report
-------------------
t/06_role_attributes.t  (Wstat: 256 Tests: 0 Failed: 0)
Non-zero exit status: 1
  Parse errors: No plan found in TAP output
Files=31, Tests=183,  39 wallclock secs
Result: FAILED
===> Testing [FAIL]: Data::Dump::Tree:ver('1.5.2'):auth('github:nkh')
Aborting due to test failure: Data::Dump::Tree:ver('1.5.2'):auth('github:nkh') (use --force-test to override)
  in code  at /path/bio/informatics-core/apps/rakudo-star/rakudo-star-2017.07/install/share/perl6/site/sources/3393EDA469A9E8925A633FF7A533AB41141495DA (Zef::Client) line 373
  in method test at /path/bio/informatics-core/apps/rakudo-star/rakudo-star-2017.07/install/share/perl6/site/sources/3393EDA469A9E8925A633FF7A533AB41141495DA (Zef::Client) line 351
  in code  at /path/bio/informatics-core/apps/rakudo-star/rakudo-star-2017.07/install/share/perl6/site/sources/3393EDA469A9E8925A633FF7A533AB41141495DA (Zef::Client) line 528
  in sub  at /path/bio/informatics-core/apps/rakudo-star/rakudo-star-2017.07/install/share/perl6/site/sources/3393EDA469A9E8925A633FF7A533AB41141495DA (Zef::Client) line 525
  in method install at /path/bio/informatics-core/apps/rakudo-star/rakudo-star-2017.07/install/share/perl6/site/sources/3393EDA469A9E8925A633FF7A533AB41141495DA (Zef::Client) line 631
  in sub MAIN at /path/bio/informatics-core/apps/rakudo-star/rakudo-star-2017.07/install/share/perl6/site/sources/ED3033E8712BCF9F6DE53678B14A54705DF211A6 (Zef::CLI) line 152
  in block <unit> at /path/bio/informatics-core/apps/rakudo-star/rakudo-star-2017.07/install/share/perl6/site/resources/6182CA1C8C9C6ED5BBB3076B522103070B37DDA4 line 1
  in sub MAIN at /path/bio/informatics-core/apps/rakudo-star/rakudo-star-2017.07/install/share/perl6/site/bin/zef line 2
  in block <unit> at /path/bio/informatics-core/apps/rakudo-star/rakudo-star-2017.07/install/share/perl6/site/bin/zef line 2
```

**Comment by nkh** [comment] 2017-08-09 14:48
There is no such line in the latest 06_role_attributes.t, I copied the
first lines of that file below.

Try a zef uninstall Data::Dump::Tree.

BTW, there are three issues I kjnow of, so you don't lose patience,

 - this one, which seems to be a version problem
 - 04_flat.t failing if you do not have Term::ANSIColor installed (I am
working on fixing it)
 - Test::Meta not finding META6, version 0.0.4, that's not related to
Data::Dump::Tree but if you encounter it I can help you  fix it

I should have version out within 2 hours or so.

thank you for your feedback, Nadim.

PS: what version of rakudo are you using? from a distro or building it
yourself?


>>>

use Test ;
use Data::Dump::Tree ;

plan 11 ;

class edible { has $taste = 1 / 3 ; }
class Fruit is edible { has $.seeds }
role Tomato {has $.color = 'red'} ;
<<<

**Comment by molecules** [comment] 2017-08-09 14:56
I'm using Rakudo Star 2017.07 which I built from https://rakudo.perl6.org/downloads/star/rakudo-star-2017.07.tar.gz.

```
$ perl6 --version
This is Rakudo version 2017.07 built on MoarVM version 2017.07
implementing Perl 6.c.
```

I'm using CentOS Linux release 7.3.1611 (Core)

(see my answer at https://stackoverflow.com/a/45548095/215487 if you want more details, or I can post them here if you're interested)

**Comment by nkh** [comment] 2017-08-09 15:45
I have just updated version 1.5.4, that's the one Zef should try to install.

The three problems above should be fixed. but I need you to confirm for the DDT not found problem that should already be fixed in the previous versions.

I recommend a zef uninstall Data::Dump::Tree, although it should not find it at all.

I asked about the rakudo version because I use a bleeding edge in my development and tests, aka, the latest developer version.

The tests should let us know if it works with your version. But even if the tests pass, there may be a corner case that I have not caught in the 200+ tests.

With some luck all will work fine with your version. In the future I will do regression tests and list which version it works with.

Looking forward to your test results.

**Comment by molecules** [comment] 2017-08-09 16:07
```
$ zef uninstall Data::Dump::Tree
!!!> Found no matching candidates to uninstall
```
And when I try to install it using zef, I keep getting version `1.5.2`.

So, I cloned it and tried installing directly:

```
git clone git@github.com:nkh/P6-Data-Dump-Tree.git
cd P6-Data-Dump-Tree
zef install .
```

Now it works great. Thanks!

**Comment by nkh** [comment] 2017-08-09 16:10
You are welcome.

can you please confirm that in your clone repo the version is set to 1.5.3 in META6.json?

**Comment by nkh** [comment] 2017-08-09 16:11
actually it's 1.5.4 in the latest

**Comment by molecules** [comment] 2017-08-09 16:12
Yes it is 1.5.4.

**Comment by nkh** [comment] 2017-08-09 16:15
installed Term::ANSIColor if you want the best results, You can try without and then try with to see the difference if you want to. There is also option :color and :!color if you want to control it.

I recommend looking in the example directory, there's a READ.me, it shows a lot of examples.

display of more complex data can require a filter for best results, there are examples but if you get stuck I am happy to help.

**Comment by molecules** [comment] 2017-08-09 16:23
Thanks! This is great! I'll let you know if I have questions. Thanks so much for developing and maintaining this module!

I'm getting ready to make a module or two of my own. Is the following probably a good place to start (as far as tutorials go)? Do you have any additional pointers?

http://blogs.perl.org/users/zoffix_znet/2016/02/how-to-make-a-perl-6-module-bit-rot-thursday.html

**Comment by nkh** [comment] 2017-08-09 16:29
https://docs.perl6.org/language/modules
https://docs.perl6.org/language/modules-extra

Good requirements.

Tests! And testing the install process, and good documentation.

And patience.

**Comment by molecules** [comment] 2017-08-09 16:34
Thanks!
